### PR TITLE
add docs for how to specificy credentials

### PR DESCRIPTION
**Pull request by grosser**
@chrisroberts had to look that up in the code ... don't want others to have to do the same ...

### CODE REVIEW

**Comment by luckymike** [comment]
@grosser this is actually in the Docs: http://www.sparkleformation.io/docs/sfn/configuration.html#sfn-based

**Comment by grosser** [comment]
`Description	API credentials for target orchestration API, Valid	Hash` how do I know what sfn wants the hash on the commandline to look like ?

also the --help output does not mention that it needs a hash ...
`    -C, --credentials                 Provider credentials`

FYI using thor instead of this homegrown CLI framework would make this all easier and a bit more standardized ...

**Comment by luckymike** [comment]
Ah, I see what you're trying to address now. I'm not sure the update in this PR will provide much additional help; however, as you'd still need to know the key-value pairs to specify, i.e. what the heck provider credentials are. 

It does probably make sense for us to document the general expectations for multiple key-value pairs on the command line.

**Comment by chrisroberts** [comment]
Addressed the format in option description within #90 to keep it consistent with other similar uses. Thanks!

**Pull request closed without merging**
