### PR TITLE
I think lines 77-end of lib/sfn/command/create.rb choke on 500 server errors from AWS

### PR DESCRIPTION
**Pull request by chrisroberts**
Launched a successful stack, but while polling I got a 500 error from AWS.  That triggered display_instance_failure in lib/sfn/config/inspect.rb, which blew up because it couldn't find any failed instances?

+ bundle exec sfn create -f stacks/cloudformation/output/databases_dr_us-west-2.json -r DatabaseInstancesEbsOptimized:true -r DatabaseInstanceType:r3.4xlarge -r ThirddatabaseInstancesEbsOptimized:true -r ThirddatabaseInstanceType:r3.4xlarge -d indigo-dr-tokumx-us-west-2-45
Unexpected error encountered (Miasma::Error::ApiError::RequestError: Internal Server Error) Retrying [retry count: 1]
ERROR: RuntimeError: 
[32m[Sfn]:[0m [1mCloud Formation:[0m [32mcreate[0m
[32m[Sfn]:[0m   -> [1mName:[0m indigo-dr-tokumx-us-west-2-45
[32m[Sfn]:[0m Events for Stack: [1mindigo-dr-tokumx-us-west-2-45[0m
[1mTime                     [0m [1mResource Logical Id            [0m [1mResource Status     [0m [1mResource Status Reason  [0m 
2015-08-25 13:15:34 UTC   indigo-dr-tokumx-us-west-2-45   CREATE_IN_PROGRESS   User Initiated           
2015-08-25 13:15:39 UTC   DatabaseIamInstanceRole         CREATE_IN_PROGRESS                            
2015-08-25 13:15:49 UTC   DatabaseIamInstanceRole         CREATE_IN_PROGRESS   Resource creation Initiated   
2015-08-25 13:15:50 UTC   DatabaseIamInstanceRole         CREATE_COMPLETE                                    
2015-08-25 13:15:51 UTC   DatabaseIamInstancePolicy       CREATE_IN_PROGRESS                                 
2015-08-25 13:15:52 UTC   DatabaseIamInstancePolicy       CREATE_COMPLETE                                    
2015-08-25 13:15:52 UTC   DatabaseIamInstancePolicy       CREATE_IN_PROGRESS   Resource creation Initiated   
2015-08-25 13:15:54 UTC   DatabaseIamInstanceProfile      CREATE_IN_PROGRESS                                 
2015-08-25 13:15:55 UTC   DatabaseIamInstanceProfile      CREATE_IN_PROGRESS   Resource creation Initiated   
2015-08-25 13:17:56 UTC   DatabaseIamInstanceProfile      CREATE_COMPLETE                                    
2015-08-25 13:17:58 UTC   ThirddatabaseLaunchConfig       CREATE_IN_PROGRESS   Resource creation Initiated   
2015-08-25 13:17:58 UTC   DatabaseLaunchConfig            CREATE_IN_PROGRESS   Resource creation Initiated   
2015-08-25 13:17:58 UTC   DatabaseLaunchConfig            CREATE_IN_PROGRESS                                 
2015-08-25 13:17:58 UTC   ThirddatabaseLaunchConfig       CREATE_IN_PROGRESS                                 
2015-08-25 13:17:59 UTC   ThirddatabaseLaunchConfig       CREATE_COMPLETE                                    
2015-08-25 13:17:59 UTC   DatabaseLaunchConfig            CREATE_COMPLETE                                    
2015-08-25 13:18:00 UTC   DatabaseAsg                     CREATE_IN_PROGRESS                                 
2015-08-25 13:18:02 UTC   DatabaseAsg                     CREATE_IN_PROGRESS   Resource creation Initiated   
2015-08-25 13:28:55 UTC   DatabaseAsg                     CREATE_IN_PROGRESS   Received SUCCESS signal with UniqueId i-2b0865ee   
2015-08-25 13:29:17 UTC   DatabaseAsg                     CREATE_IN_PROGRESS   Received SUCCESS signal with UniqueId i-91a61b4a   
2015-08-25 13:29:30 UTC   DatabaseAsg                     CREATE_COMPLETE                                                         
2015-08-25 13:29:32 UTC   ThirddatabaseAsg                CREATE_IN_PROGRESS                                                      
2015-08-25 13:29:33 UTC   ThirddatabaseAsg                CREATE_IN_PROGRESS   Resource creation Initiated                        
[32m[Sfn]:[0m Events for Stack: [1mindigo-dr-tokumx-us-west-2-45[0m
[1mTime                     [0m [1mResource Logical Id            [0m [1mResource Status     [0m [1mResource Status Reason                            [0m 
2015-08-25 13:15:34 UTC   indigo-dr-tokumx-us-west-2-45   CREATE_IN_PROGRESS   User Initiated                                     
2015-08-25 13:15:39 UTC   DatabaseIamInstanceRole         CREATE_IN_PROGRESS                                                      
2015-08-25 13:15:49 UTC   DatabaseIamInstanceRole         CREATE_IN_PROGRESS   Resource creation Initiated                        
2015-08-25 13:15:50 UTC   DatabaseIamInstanceRole         CREATE_COMPLETE                                                         
2015-08-25 13:15:51 UTC   DatabaseIamInstancePolicy       CREATE_IN_PROGRESS                                                      
2015-08-25 13:15:52 UTC   DatabaseIamInstancePolicy       CREATE_COMPLETE                                                         
2015-08-25 13:15:52 UTC   DatabaseIamInstancePolicy       CREATE_IN_PROGRESS   Resource creation Initiated                        
2015-08-25 13:15:54 UTC   DatabaseIamInstanceProfile      CREATE_IN_PROGRESS                                                      
2015-08-25 13:15:55 UTC   DatabaseIamInstanceProfile      CREATE_IN_PROGRESS   Resource creation Initiated                        
2015-08-25 13:17:56 UTC   DatabaseIamInstanceProfile      CREATE_COMPLETE                                                         
2015-08-25 13:17:58 UTC   ThirddatabaseLaunchConfig       CREATE_IN_PROGRESS   Resource creation Initiated                        
2015-08-25 13:17:58 UTC   DatabaseLaunchConfig            CREATE_IN_PROGRESS   Resource creation Initiated                        
2015-08-25 13:17:58 UTC   DatabaseLaunchConfig            CREATE_IN_PROGRESS                                                      
2015-08-25 13:17:58 UTC   ThirddatabaseLaunchConfig       CREATE_IN_PROGRESS                                                      
2015-08-25 13:17:59 UTC   ThirddatabaseLaunchConfig       CREATE_COMPLETE                                                         
2015-08-25 13:17:59 UTC   DatabaseLaunchConfig            CREATE_COMPLETE                                                         
2015-08-25 13:18:00 UTC   DatabaseAsg                     CREATE_IN_PROGRESS                                                      
2015-08-25 13:18:02 UTC   DatabaseAsg                     CREATE_IN_PROGRESS   Resource creation Initiated                        
2015-08-25 13:28:55 UTC   DatabaseAsg                     CREATE_IN_PROGRESS   Received SUCCESS signal with UniqueId i-2b0865ee   
2015-08-25 13:29:17 UTC   DatabaseAsg                     CREATE_IN_PROGRESS   Received SUCCESS signal with UniqueId i-91a61b4a   
2015-08-25 13:29:30 UTC   DatabaseAsg                     CREATE_COMPLETE                                                         
2015-08-25 13:29:32 UTC   ThirddatabaseAsg                CREATE_IN_PROGRESS                                                      
2015-08-25 13:29:33 UTC   ThirddatabaseAsg                CREATE_IN_PROGRESS   Resource creation Initiated                        
[31;1m[FATAL]:[0m Create of new stack [1mindigo-dr-tokumx-us-west-2-45[0m: [31;1mFAILED[0m
[32m[Sfn]:[0m 
[32m[Sfn]:[0m Stack inspection [1mindigo-dr-tokumx-us-west-2-45[0m:
[31;1m[ERROR]:[0m Failed to locate any failed instances

### CODE REVIEW

**Comment by chrisroberts** [comment]
well, i'm not sure what i was expecting `hub` to do by providing an issue with the PR creation, but converting it like this wasn't quite what i imagined. anyway, just going to roll with it and hijack this issue :smile:

**Comment by luckymike** [comment]
lol whut?

**Comment by chrisroberts** [comment]
Retry behavior can be configured via configuration file _only_. It defaults to an exponential backoff, and allows for 20 retries. README updated with valid configuration bits. Configuration can allow for infinite retries.

retry forever

**Comment by gswallow** [comment]
Thanks.  I should have contributed a pull request because I totally could have, but I've had other stuff to work on.  I really do appreciate it.

**Pull request merged**
