### PR TITLE
Restrict bundler auto require to sfn group

### PR DESCRIPTION
**Pull request by chrisroberts**
Prevents loading default gems re: #170

### CODE REVIEW

**Comment by grosser** [comment]
:+1:

**Comment by luckymike** [comment]
:+1: _technically_ a breaking change, right?

**Comment by grosser** [comment]
will blow up for some repos ... but should be straight forward to fix

**Comment by luckymike** [comment]
Breaking is breaking, though. I think it's a good change, I just don't think we should be cavalier in rolling it out as sudden failures, even if easy to fix, reflect negatively on our software.

If we're going to put it in 2.x, can this be extended to load the entire bundle _unless_ the `:sfn` group is present? That would preserve current functionality while also allowing those users who would like to reduce the loaded gemset to do so quite easily.

**Comment by luckymike** [comment]
See #172, which should preserve existing behavior while also supporting just the `:sfn` group.

**Comment by chrisroberts** [comment]
Yes, this is a breaking change and that's okay. While it is an easily fixable breakage, I'll be including it within a major version bump after some fixes are merged and a 2.2 release is cut.

**Pull request merged**
